spring:
  application:
    name: gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8081
server:
  port: 8000


zuul:
  routes:
   user: user-service
   oauth: oauth2