spring:
  application:
    name: gateway
  cache:
    type: ehcache
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8880
server:
  port: 8880

auth:
#  route:
#    enable: true
  forwardHeader: user
  requestHeader:
  sessionIn: cookie
  sessionId: SESSION
  loginUrl: /auth/login.html
#  tokenUrl: /auth/token
#  authService: http://localhost:8080
#  unFilter: /auth/**


zuul:
  routes:
#    user-service:
#      path: /user/**
#      url: http://localhost:8082/
    user-service: /user/**
    note-service: /note/**
#    auth-service: /auth/**
  ignored-patterns: /*/api/**,/**/*.html


file:
  upload:
    path: /home/data/xnote/upload