spring:
  application:
    name: oauth2
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
#    cache-names: simple
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8081
server:
  port: 8090
