spring:
  application:
    name: user-service
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
#  cloud:
#    config:
#     uri: http://localhost:8888/
#     profile:
#     label:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8082
server:
  port: 8082

auth:
  client:
    enable: true
  forwardHeader: user