spring:
  application:
    name: note-service
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml

  datasource:
    url: jdbc:mysql://47.94.106.96/ideal?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: mysql
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#  cloud:
#    config:
#     uri: http://localhost:8888/
#     profile:
#     label:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8082
server:
  port: 8082

auth:
  client:
    enable: true
  forwardHeader: user


file:
  upload:
    path: /home/data/xnote/upload